### ISSUE TITLE
Serverlist output always empty

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/multiplayer.rigsofrods.org#6]
Reported by @Michael10055 in Gitter chatroom 

> right now the server list isn't working properly. The server registers successfully (and is sending heartbeats) but it doesn't show up  on the list:  http://multiplayer.rigsofrods.org/server-list

**Comment by AnotherFoxGuy** [comment]
There was a typo in the configuration file, the server list should be working again.
